"""Add new column to clubs

Revision ID: 908ccc253570
Revises: 7e6080e9031a
Create Date: 2022-01-26 14:49:57.558928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '908ccc253570'
down_revision = '7e6080e9031a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('xga', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clubs', 'xga')
    # ### end Alembic commands ###
