"""update schema

Revision ID: aa7eae0e43a4
Revises: 878949028408
Create Date: 2022-03-07 09:29:10.458728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa7eae0e43a4'
down_revision = '878949028408'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs',
    sa.Column('team', sa.Numeric(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('matches', sa.Numeric(), nullable=False),
    sa.Column('wins', sa.Numeric(), nullable=False),
    sa.Column('draws', sa.Numeric(), nullable=False),
    sa.Column('loses', sa.Numeric(), nullable=False),
    sa.Column('goals_scored', sa.Numeric(), nullable=False),
    sa.Column('goals_conceded', sa.Numeric(), nullable=False),
    sa.Column('pts', sa.Numeric(), nullable=False),
    sa.Column('xG', sa.Numeric(), nullable=False),
    sa.Column('xG_diff', sa.Numeric(), nullable=False),
    sa.Column('npxG', sa.Numeric(), nullable=False),
    sa.Column('xGA', sa.Numeric(), nullable=False),
    sa.Column('xGA_diff', sa.Numeric(), nullable=False),
    sa.Column('npxGA', sa.Numeric(), nullable=False),
    sa.Column('npxGD', sa.Numeric(), nullable=False),
    sa.Column('ppda_coef', sa.Numeric(), nullable=False),
    sa.Column('oppda_coef', sa.Numeric(), nullable=False),
    sa.Column('deep', sa.Numeric(), nullable=False),
    sa.Column('deep_allowed', sa.Numeric(), nullable=False),
    sa.Column('xpts', sa.Numeric(), nullable=False),
    sa.Column('xpts_dif', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('team')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('game', sa.Numeric(), nullable=False),
    sa.Column('time', sa.Numeric(), nullable=False),
    sa.Column('goals', sa.Numeric(), nullable=False),
    sa.Column('xG', sa.Numeric(), nullable=False),
    sa.Column('assists', sa.Numeric(), nullable=False),
    sa.Column('xA', sa.Numeric(), nullable=False),
    sa.Column('shots_taken', sa.Numeric(), nullable=False),
    sa.Column('key_passes', sa.Numeric(), nullable=False),
    sa.Column('yellow_cards', sa.Numeric(), nullable=False),
    sa.Column('red_cards', sa.Numeric(), nullable=False),
    sa.Column('position', sa.Numeric(), nullable=False),
    sa.Column('team_title', sa.String(), nullable=True),
    sa.Column('npg', sa.Numeric(), nullable=False),
    sa.Column('npxG', sa.Numeric(), nullable=False),
    sa.Column('xGChain', sa.Numeric(), nullable=False),
    sa.Column('xGBuildup', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['team_title'], ['clubs.team'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    op.drop_table('clubs')
    # ### end Alembic commands ###
