"""update players table

Revision ID: 878949028408
Revises: f463d811e602
Create Date: 2022-03-04 16:54:12.870379

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "878949028408"
down_revision = "f463d811e602"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    for table in ("clubs_delete", "players"):
        op.drop_table(table)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("players", sa.Column("club_id", sa.INTEGER(), nullable=True))
    op.add_column("players", sa.Column("is_active_club", sa.BOOLEAN(), nullable=True))
    op.add_column(
        "players", sa.Column("value", sa.NUMERIC(precision=10, scale=2), nullable=True)
    )
    op.add_column("players", sa.Column("nationality", sa.VARCHAR(), nullable=True))
    op.add_column("players", sa.Column("age", sa.INTEGER(), nullable=True))
    op.add_column("players", sa.Column("name", sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, "players", type_="foreignkey")
    op.create_foreign_key(None, "players", "clubs", ["club_id"], ["id"])
    op.drop_column("players", "xGBuildup")
    op.drop_column("players", "xGChain")
    op.drop_column("players", "npxG")
    op.drop_column("players", "npg")
    op.drop_column("players", "team_title")
    op.drop_column("players", "position")
    op.drop_column("players", "red_cards")
    op.drop_column("players", "yellow_cards")
    op.drop_column("players", "key_passes")
    op.drop_column("players", "shots_taken")
    op.drop_column("players", "xA")
    op.drop_column("players", "assists")
    op.drop_column("players", "xG")
    op.drop_column("players", "goals")
    op.drop_column("players", "time")
    op.drop_column("players", "game")
    op.drop_column("players", "player_name")
    op.add_column("clubs", sa.Column("id", sa.INTEGER(), nullable=False))
    op.create_table(
        "stats",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("player_id", sa.INTEGER(), nullable=True),
        sa.Column("no_assists", sa.INTEGER(), nullable=True),
        sa.Column("no_goals", sa.INTEGER(), nullable=True),
        sa.Column("yellow_cards", sa.INTEGER(), nullable=True),
        sa.Column("red_cards", sa.INTEGER(), nullable=True),
        sa.Column("games_played", sa.INTEGER(), nullable=True),
        sa.Column("average_rating", sa.NUMERIC(precision=2, scale=2), nullable=True),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("player_id"),
    )
    # ### end Alembic commands ###
