"""create base schema

Revision ID: f463d811e602
Revises: 
Create Date: 2022-01-31 14:26:18.693970

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f463d811e602"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clubs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("position", sa.String(), nullable=False),
        sa.Column("team", sa.Numeric(), nullable=False),
        sa.Column("matches", sa.Numeric(), nullable=False),
        sa.Column("wins", sa.Numeric(), nullable=False),
        sa.Column("draws", sa.Numeric(), nullable=False),
        sa.Column("loses", sa.Numeric(), nullable=False),
        sa.Column("goals_scored", sa.Numeric(), nullable=False),
        sa.Column("goals_conceded", sa.Numeric(), nullable=False),
        sa.Column("pts", sa.Numeric(), nullable=False),
        sa.Column("xG", sa.Numeric(), nullable=False),
        sa.Column("xG_diff", sa.Numeric(), nullable=False),
        sa.Column("npxG", sa.Numeric(), nullable=False),
        sa.Column("xGA", sa.Numeric(), nullable=False),
        sa.Column("xGA_diff", sa.Numeric(), nullable=False),
        sa.Column("npxGA", sa.Numeric(), nullable=False),
        sa.Column("npxGD", sa.Numeric(), nullable=False),
        sa.Column("ppda_coef", sa.Numeric(), nullable=False),
        sa.Column("oppda_coef", sa.Numeric(), nullable=False),
        sa.Column("deep", sa.Numeric(), nullable=False),
        sa.Column("deep_allowed", sa.Numeric(), nullable=False),
        sa.Column("xpts", sa.Numeric(), nullable=False),
        sa.Column("xpts_dif", sa.Numeric(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "players",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("club_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("nationality", sa.String(), nullable=True),
        sa.Column("value", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("is_active_club", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["club_id"],
            ["clubs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "stats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=True),
        sa.Column("no_assists", sa.Integer(), nullable=True),
        sa.Column("no_goals", sa.Integer(), nullable=True),
        sa.Column("yellow_cards", sa.Integer(), nullable=True),
        sa.Column("red_cards", sa.Integer(), nullable=True),
        sa.Column("games_played", sa.Integer(), nullable=True),
        sa.Column("average_rating", sa.Numeric(precision=2, scale=2), nullable=True),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("player_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("stats")
    op.drop_table("players")
    op.drop_table("clubs")
    # ### end Alembic commands ###


# Form for skills, everyone's specialism's
